// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ8YcfSvWXOEjL1MfnSsE_SlG46PsaTdM',
    appId: '1:807032923836:web:1c339259ad47d1698f12b9',
    messagingSenderId: '807032923836',
    projectId: 'runtogetherapp-e8397',
    authDomain: 'runtogetherapp-e8397.firebaseapp.com',
    storageBucket: 'runtogetherapp-e8397.firebasestorage.app',
    measurementId: 'G-2FJCRFHT9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWFEHuqKgqYO6QO7bgtkfYj7s7rn2tXO0',
    appId: '1:807032923836:android:d0312e99ee00b2f78f12b9',
    messagingSenderId: '807032923836',
    projectId: 'runtogetherapp-e8397',
    storageBucket: 'runtogetherapp-e8397.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNLSzuq2BHmub3a5BCpK6lcHHZyuhYR5g',
    appId: '1:807032923836:ios:1957227861dbd4d78f12b9',
    messagingSenderId: '807032923836',
    projectId: 'runtogetherapp-e8397',
    storageBucket: 'runtogetherapp-e8397.firebasestorage.app',
    iosBundleId: 'com.example.runtogetherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNLSzuq2BHmub3a5BCpK6lcHHZyuhYR5g',
    appId: '1:807032923836:ios:1957227861dbd4d78f12b9',
    messagingSenderId: '807032923836',
    projectId: 'runtogetherapp-e8397',
    storageBucket: 'runtogetherapp-e8397.firebasestorage.app',
    iosBundleId: 'com.example.runtogetherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ8YcfSvWXOEjL1MfnSsE_SlG46PsaTdM',
    appId: '1:807032923836:web:410d29cb7681a0a78f12b9',
    messagingSenderId: '807032923836',
    projectId: 'runtogetherapp-e8397',
    authDomain: 'runtogetherapp-e8397.firebaseapp.com',
    storageBucket: 'runtogetherapp-e8397.firebasestorage.app',
    measurementId: 'G-XBYRT13H6N',
  );

}